---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xy.
--- DateTime: 2021/3/29 17:51
---
GoodsData = Class("GoodsData")

function GoodsData:ctor()
    self.uid = nil -- 商品id
    self.PathPrefab = nil --模板路径
    self.CS_Template = nil -- 模板UITemplate组件
    self.CC = {} -- 模板缓存组建列表
    self.HasInit = false
    self.Data = nil -- 模板数据
    self.CE = {}
end