---@class Cgdex3LocalData
Cgdex3LocalData = {
sortid = 0,
typeid = 0,
chapterid = 0,
chaptername = "0",
chaptersort = 0,
name = "0",
music = "0",
checkpointid = 0,
time = "0",
chapterpic = "0",
}
---@type Cgdex3LocalData[]
Cgdex3LocalData.tab = {
[1] = {sortid = 1, typeid = 99, chapterid = 0, chaptername = "專輯 - 時間之外", chaptersort = 1, name = "Hidden", music = "6-Thehiddentruth_MP3", checkpointid = 0, time = "01,50", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji1", "0", "0", "0", "许是终幕"},
[2] = {sortid = 2, typeid = 99, chapterid = 0, chaptername = "專輯 - 時間之外", chaptersort = 2, name = "霾", music = "7-Undertheearth_MP3", checkpointid = 0, time = "02,00", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji1", "0", "0", "0", "领航星"},
[3] = {sortid = 3, typeid = 99, chapterid = 0, chaptername = "專輯 - 時間之外", chaptersort = 3, name = "Ruin of an illusion", music = "12-ruins_MP3", checkpointid = 0, time = "01,56", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji1", "0", "0", "0", "月面续存"},
[4] = {sortid = 4, typeid = 99, chapterid = 0, chaptername = "專輯 - 時間之外", chaptersort = 4, name = "Abysmal sea", music = "22-nest_MP3", checkpointid = 0, time = "01,52", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji1", "0", "0", "0", "Over the moon"},
[5] = {sortid = 5, typeid = 99, chapterid = 1, chaptername = "專輯 - 蒼穹戰線", chaptersort = 1, name = "Warehouse", music = "3-juesejiemian_MP3", checkpointid = 100001, time = "01,52", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2", "0", "0", "0", "Hidden"},
[6] = {sortid = 6, typeid = 99, chapterid = 1, chaptername = "專輯 - 蒼穹戰線", chaptersort = 2, name = "午茶", music = "25-Lowtea_MP3", checkpointid = 100001, time = "01,52", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2", "0", "0", "0", "霾"},
[7] = {sortid = 7, typeid = 99, chapterid = 1, chaptername = "專輯 - 蒼穹戰線", chaptersort = 3, name = "許是終幕", music = "1-Afterallthestories_MP3", checkpointid = 100008, time = "02,09", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2", "0", "0", "0", "Deception"},
[8] = {sortid = 8, typeid = 99, chapterid = 1, chaptername = "專輯 - 蒼穹戰線", chaptersort = 4, name = "Echo", music = "13-Reverb_MP3", checkpointid = 100008, time = "02,15", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2", "0", "0", "0", "【逆爱】"},
[9] = {sortid = 9, typeid = 99, chapterid = 1, chaptername = "專輯 - 蒼穹戰線", chaptersort = 5, name = "月面續存", music = "4-Battle-moon_MP3", checkpointid = 100021, time = "01,52", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2", "0", "0", "0", "Pierce the haze"},
[10] = {sortid = 10, typeid = 99, chapterid = 1, chaptername = "專輯 - 蒼穹戰線", chaptersort = 6, name = "間奏二", music = "20-Battle-Warehouse2_MP3", checkpointid = 100021, time = "01,39", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2", "0", "0", "0", "Melpomene"},
[11] = {sortid = 11, typeid = 99, chapterid = 1, chaptername = "專輯 - 蒼穹戰線", chaptersort = 7, name = "Over the moon", music = "5-overthemoon_MP3", checkpointid = 100021, time = "02,00", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2", "0", "0", "0", "残响其一"},
[12] = {sortid = 12, typeid = 99, chapterid = 1, chaptername = "專輯 - 蒼穹戰線", chaptersort = 8, name = "【逆愛】", music = "9-Battle-niai", checkpointid = 100031, time = "02,02", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2", "0", "0", "0", "Ruin of an illusion"},
[13] = {sortid = 13, typeid = 99, chapterid = 1, chaptername = "專輯 - 蒼穹戰線", chaptersort = 9, name = "Deception", music = "8-Deception_MP3", checkpointid = 100033, time = "02,00", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2", "0", "0", "0", "Heroic epic"},
[14] = {sortid = 14, typeid = 99, chapterid = 1, chaptername = "專輯 - 蒼穹戰線", chaptersort = 10, name = "殘響其一", music = "0-pv_MP3", checkpointid = 100039, time = "02,20", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2", "0", "0", "0", "Unstoppable"},
[15] = {sortid = 15, typeid = 99, chapterid = 2, chaptername = "專輯 - 濃霧港灣", chaptersort = 1, name = "回收策略", music = "Battle-ziyuan_MP3", checkpointid = 100101, time = "02,08", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji3", "0", "0", "0", "间奏二"},
[16] = {sortid = 16, typeid = 99, chapterid = 2, chaptername = "專輯 - 濃霧港灣", chaptersort = 2, name = "領航星", music = "2-zhujiemian_MP3", checkpointid = 100103, time = "02,26", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji3", "0", "0", "0", "间奏三"},
[17] = {sortid = 17, typeid = 99, chapterid = 2, chaptername = "專輯 - 濃霧港灣", chaptersort = 3, name = "間奏三", music = "21-Battle-Warehouse3_MP3", checkpointid = 100104, time = "01,38", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji3", "0", "0", "0", "Abysmal sea"},
[18] = {sortid = 18, typeid = 99, chapterid = 2, chaptername = "專輯 - 濃霧港灣", chaptersort = 4, name = "間奏一", music = "19-Battle-Warehouse_MP3", checkpointid = 100128, time = "01,53", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji3", "0", "0", "0", "微乎其微的抗争"},
[19] = {sortid = 19, typeid = 99, chapterid = 2, chaptername = "專輯 - 濃霧港灣", chaptersort = 5, name = "Heroic epic", music = "15-Battle-Sobek_MP3", checkpointid = 100134, time = "01,53", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji3", "0", "0", "0", "Distantblue"},
[20] = {sortid = 20, typeid = 99, chapterid = 3, chaptername = "專輯 - 海市蜃樓", chaptersort = 1, name = "Twerp", music = "26-twerp_MP3", checkpointid = 100200, time = "01,43", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji4", "0", "0", "0", "午茶"},
[21] = {sortid = 21, typeid = 99, chapterid = 3, chaptername = "專輯 - 海市蜃樓", chaptersort = 2, name = "Melpomene", music = "11-Mnemosyne_MP3", checkpointid = 100211, time = "02,05", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji4", "0", "0", "0", "Warehouse"},
[22] = {sortid = 22, typeid = 99, chapterid = 3, chaptername = "專輯 - 海市蜃樓", chaptersort = 3, name = "Pierce the haze", music = "10-Piercethehaze_MP3", checkpointid = 100241, time = "01,54", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji4", "0", "0", "0", "Echo"},
[23] = {sortid = 23, typeid = 99, chapterid = 3, chaptername = "專輯 - 海市蜃樓", chaptersort = 4, name = "Unstoppable", music = "16-Battle-Jormungand_MP3", checkpointid = 100252, time = "01,53", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji4", "0", "0", "0", "Twerp"},
[24] = {sortid = 24, typeid = 99, chapterid = 3, chaptername = "專輯 - 海市蜃樓", chaptersort = 5, name = "微乎其微的抗爭", music = "23-light_MP3", checkpointid = 100253, time = "01,32", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji4", "0", "0", "0", "回收策略"},
[25] = {sortid = 25, typeid = 99, chapterid = 4, chaptername = "專輯 - 心之所向", chaptersort = 1, name = "Distantblue", music = "24-Distantbluesea_MP3", checkpointid = 100346, time = "01,57", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji5", "0", "0", "0", "间奏一"},
[26] = {sortid = 26, typeid = 99, chapterid = 4, chaptername = "專輯 - 心之所向", chaptersort = 2, name = "安潔莉卡", music = "17-Battle-jidu_MP3", checkpointid = 100348, time = "01,55", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji5", "0", "0", "0", "0"},
[27] = {sortid = 27, typeid = 99, chapterid = 5, chaptername = "專輯 - 黑色幽靈", chaptersort = 1, name = "Temporary Calm", music = "41-Maya-now", checkpointid = 100400, time = "01,00", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji6", "0", "0", "0", "间奏一"},
[28] = {sortid = 28, typeid = 99, chapterid = 5, chaptername = "專輯 - 黑色幽靈", chaptersort = 2, name = "危機", music = "42-Battle-crisis", checkpointid = 100400, time = "01,01", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji6", "0", "0", "0", "0"},
[29] = {sortid = 29, typeid = 99, chapterid = 5, chaptername = "專輯 - 黑色幽靈", chaptersort = 3, name = "NewBorn", music = "39-Battle-Skoll", checkpointid = 100426, time = "01,09", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji6", "0", "0", "0", "间奏一"},
[30] = {sortid = 30, typeid = 99, chapterid = 5, chaptername = "專輯 - 黑色幽靈", chaptersort = 4, name = "Accelerate", music = "40-Battle-Maya", checkpointid = 100426, time = "01,00", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji6", "0", "0", "0", "0"},
[31] = {sortid = 31, typeid = 99, chapterid = 6, chaptername = "專輯 - 謬誤器皿", chaptersort = 1, name = "Spooky", music = "58-spooky", checkpointid = 100506, time = "02,01", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji7", "0", "0", "0", "0"},
[32] = {sortid = 32, typeid = 99, chapterid = 6, chaptername = "專輯 - 謬誤器皿", chaptersort = 2, name = "坦白", music = "46-confess", checkpointid = 100519, time = "02,01", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji7", "0", "0", "0", "0"},
[33] = {sortid = 33, typeid = 99, chapterid = 6, chaptername = "專輯 - 謬誤器皿", chaptersort = 3, name = "Swamp Dweller", music = "70-Battle_Fenrir", checkpointid = 100549, time = "00,54", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji7", "0", "0", "0", "0"},
[34] = {sortid = 34, typeid = 99, chapterid = 7, chaptername = "專輯 - 窮途末路", chaptersort = 1, name = "準備好了嗎？", music = "76-Ready_or_not", checkpointid = 100649, time = "02,14", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji8", "0", "0", "0", "0"},
[35] = {sortid = 35, typeid = 99, chapterid = 7, chaptername = "專輯 - 窮途末路", chaptersort = 2, name = "混沌的現實", music = "60-Chaotic-reality", checkpointid = 100649, time = "02,22", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji8", "0", "0", "0", "0"},
[36] = {sortid = 36, typeid = 99, chapterid = 7, chaptername = "專輯 - 窮途末路", chaptersort = 3, name = "Starry", music = "45-antinova_full", checkpointid = 100649, time = "02,06", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji8", "0", "0", "0", "0"},
[37] = {sortid = 37, typeid = 99, chapterid = 7, chaptername = "專輯 - 窮途末路", chaptersort = 4, name = "最後的盛宴", music = "99-The_Last_Feast", checkpointid = 100649, time = "02,04", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji8", "0", "0", "0", "0"},
[38] = {sortid = 38, typeid = 99, chapterid = 7, chaptername = "專輯 - 窮途末路", chaptersort = 5, name = "撕碎巨口", music = "100-Break_The_Maw", checkpointid = 100649, time = "02,00", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji8", "0", "0", "0", "0"},
[39] = {sortid = 39, typeid = 99, chapterid = 100, chaptername = "專輯 - 午後與糖", chaptersort = 1, name = "靜夜", music = "28-Silent_night", checkpointid = 100039, time = "01,02", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji0", "0", "0", "0", "静夜"},
[40] = {sortid = 40, typeid = 99, chapterid = 100, chaptername = "專輯 - 午後與糖", chaptersort = 2, name = "Coffee House", music = "27-Coffee_House", checkpointid = 100101, time = "01,09", chapterpic = "ArtGallery/MusicPic/Img_Zhuanji0", "0", "0", "0", "Coffee House"},
}
return Cgdex3LocalData
