---@class LoadingimgLocalData
LoadingimgLocalData = {
sort = 0,
itemunlock = 0,
img = "0",
imgcover = "0",
imgtext = "0",
}
---@type LoadingimgLocalData[]
LoadingimgLocalData.tab = {
[1] = {sort = 1, itemunlock = 99999999, img = "ArtGallery/LoadingPic/LoadingPic_1", imgcover = "ArtGallery/Illustration256/yulan_cg1", imgtext = "默认", "0", "0"},
[2] = {sort = 2, itemunlock = 300000, img = "ArtGallery/LoadingPic/LoadingPic_2", imgcover = "ArtGallery/Illustration256/yulan_cg7", imgtext = "史蒂芬妮", "0", "0"},
[3] = {sort = 3, itemunlock = 300001, img = "ArtGallery/LoadingPic/LoadingPic_3", imgcover = "ArtGallery/Illustration256/yulan_cg10", imgtext = "懷中的吉雅", "0", "0"},
[4] = {sort = 4, itemunlock = 300002, img = "ArtGallery/LoadingPic/LoadingPic_4", imgcover = "ArtGallery/HomePic/home_yulan_fulanka", imgtext = "弗蘭卡「指揮室」", "0", "0"},
[5] = {sort = 5, itemunlock = 300003, img = "ArtGallery/LoadingPic/LoadingPic_5", imgcover = "ArtGallery/HomePic/home_yulan_chalisha", imgtext = "查麗莎「指揮室」", "0", "0"},
[6] = {sort = 6, itemunlock = 300004, img = "ArtGallery/LoadingPic/LoadingPic_6", imgcover = "ArtGallery/HomePic/home_yulan_zhuliwusi", imgtext = "朱利烏斯「指揮室」", "0", "0"},
[7] = {sort = 7, itemunlock = 300005, img = "ArtGallery/LoadingPic/LoadingPic_7", imgcover = "ArtGallery/HomePic/cz_yulan_chalisa", imgtext = "查麗莎「通感維護」", "0", "0"},
[8] = {sort = 8, itemunlock = 300006, img = "ArtGallery/LoadingPic/LoadingPic_8", imgcover = "ArtGallery/Illustration256/event_yulan_banzhounian", imgtext = "錯時回環", "0", "0"},
[9] = {sort = 9, itemunlock = 300007, img = "ArtGallery/LoadingPic/LoadingPic_9", imgcover = "ArtGallery/Illustration256/event_yulan_xingxingyueji", imgtext = "星行月脊", "0", "0"},
[10] = {sort = 10, itemunlock = 300008, img = "ArtGallery/LoadingPic/LoadingPic_10", imgcover = "ArtGallery/Illustration256/event_yulan_xingwangtanzhao", imgtext = "星往昙沼", "0", "0"},
[11] = {sort = 11, itemunlock = 300009, img = "ArtGallery/LoadingPic/LoadingPic_11", imgcover = "ArtGallery/Illustration256/event_yulan_yuemian", imgtext = "海月幻爍", "0", "0"},
[12] = {sort = 12, itemunlock = 300010, img = "ArtGallery/LoadingPic/LoadingPic_12", imgcover = "ArtGallery/Illustration256/event_yulan_qingrenjie", imgtext = "傳説中的巧克力傳説", "0", "0"},
[13] = {sort = 13, itemunlock = 300011, img = "ArtGallery/LoadingPic/LoadingPic_13", imgcover = "ArtGallery/Illustration256/event_yulan_yinzhiguo", imgtext = "影之國編年史", "0", "0"},
[14] = {sort = 14, itemunlock = 300012, img = "ArtGallery/LoadingPic/LoadingPic_yizhounian", imgcover = "ArtGallery/Illustration256/event_yulan_yizhounian1", imgtext = "珀因雷德之橋", "0", "0"},
[15] = {sort = 15, itemunlock = 300013, img = "ArtGallery/LoadingPic/LoadingPic_yizhounian_1", imgcover = "ArtGallery/Illustration256/event_yulan_yizhounian_1", imgtext = "祝聖之橋", "0", "0"},
[16] = {sort = 16, itemunlock = 300014, img = "ArtGallery/LoadingPic/LoadingPic_yizhounian_2", imgcover = "ArtGallery/Illustration256/event_yulan_yizhounian_2", imgtext = "神前決鬥", "0", "0"},
[17] = {sort = 17, itemunlock = 300015, img = "ArtGallery/LoadingPic/LoadingPic_yizhounian_3", imgcover = "ArtGallery/Illustration256/event_yulan_yizhounian_3", imgtext = "聖多瑪斯橋", "0", "0"},
[18] = {sort = 18, itemunlock = 300016, img = "ArtGallery/LoadingPic/LoadingPic_yizhounian_4", imgcover = "ArtGallery/Illustration256/event_yulan_yizhounian_4", imgtext = "畫中意", "0", "0"},
[19] = {sort = 19, itemunlock = 300017, img = "ArtGallery/LoadingPic/LoadingPic_yizhounian_5", imgcover = "ArtGallery/Illustration256/event_yulan_yizhounian_5", imgtext = "“神跡”", "0", "0"},
[20] = {sort = 20, itemunlock = 300018, img = "ArtGallery/LoadingPic/LoadingPic_yizhounian_6", imgcover = "ArtGallery/Illustration256/event_yulan_yizhounian_6", imgtext = "冠以“祈禱”之名的贖罪", "0", "0"},
[21] = {sort = 21, itemunlock = 300019, img = "ArtGallery/LoadingPic/LoadingPic_yizhounian_7", imgcover = "ArtGallery/Illustration256/event_yulan_yizhounian_7", imgtext = "亙古不易的光", "0", "0"},
[22] = {sort = 22, itemunlock = 300020, img = "ArtGallery/LoadingPic/LoadingPic_duoluolisicuozao", imgcover = "ArtGallery/Illustration256/event_yulan_duoluolisicuozao", imgtext = "多洛莉絲「通感維護」", "0", "0"},
[23] = {sort = 23, itemunlock = 300021, img = "ArtGallery/LoadingPic/LoadingPic_xuexiaozhiqian", imgcover = "ArtGallery/Illustration256/event_yulan_xuexiaozhiqian", imgtext = "雪消之前", "0", "0"},
[24] = {sort = 24, itemunlock = 300022, img = "ArtGallery/LoadingPic/LoadingPic_linzhongluochen", imgcover = "ArtGallery/Illustration256/event_yulan_linzhongluochen", imgtext = "林中落塵", "0", "0"},
[25] = {sort = 25, itemunlock = 300023, img = "ArtGallery/LoadingPic/LoadingPic_qihua", imgcover = "ArtGallery/Illustration256/event_yulan_qihua", imgtext = "於舞臺上讓你心神蕩漾", "0", "0"},
[26] = {sort = 26, itemunlock = 390000, img = "ArtGallery/LoadingPic/zjzj_0", imgcover = "ArtGallery/Illustration256/zj_yulan_0", imgtext = "雙子", "0", "0"},
[27] = {sort = 27, itemunlock = 390001, img = "ArtGallery/LoadingPic/zjzj_1", imgcover = "ArtGallery/Illustration256/zj_yulan_1", imgtext = "多瑙特別聯合部隊", "0", "0"},
[28] = {sort = 28, itemunlock = 390002, img = "ArtGallery/LoadingPic/zjzj_2", imgcover = "ArtGallery/Illustration256/zj_yulan_2", imgtext = "升降井", "0", "0"},
[29] = {sort = 29, itemunlock = 390003, img = "ArtGallery/LoadingPic/zjzj_3", imgcover = "ArtGallery/Illustration256/zj_yulan_3", imgtext = "深海", "0", "0"},
[30] = {sort = 30, itemunlock = 390004, img = "ArtGallery/LoadingPic/zjzj_4", imgcover = "ArtGallery/Illustration256/zj_yulan_4", imgtext = "立於巨物之前", "0", "0"},
[31] = {sort = 31, itemunlock = 390005, img = "ArtGallery/LoadingPic/zjzj_5", imgcover = "ArtGallery/Illustration256/zj_yulan_5", imgtext = "“大腦”", "0", "0"},
[32] = {sort = 32, itemunlock = 300024, img = "ArtGallery/LoadingPic/LoadingPic_jinluo", imgcover = "ArtGallery/Illustration256/event_yulan_jinluo", imgtext = "珊瑚叢生之處", "0", "0"},
[33] = {sort = 33, itemunlock = 300025, img = "ArtGallery/LoadingPic/LoadingPic_xiahuo2", imgcover = "ArtGallery/Illustration256/event_yulan_xiahuo2", imgtext = "海、少女、迷失地", "0", "0"},
[34] = {sort = 34, itemunlock = 300026, img = "ArtGallery/LoadingPic/LoadingPic_meimengbuzai", imgcover = "ArtGallery/Illustration256/event_yulan_meimengbuzai", imgtext = "美夢不在", "0", "0"},
[35] = {sort = 35, itemunlock = 300027, img = "ArtGallery/LoadingPic/LoadingPic_xiajianyishi", imgcover = "ArtGallery/Illustration256/event_yulan_xiajianyishi", imgtext = "峡间轶事", "0", "0"},
[36] = {sort = 36, itemunlock = 300028, img = "ArtGallery/LoadingPic/LoadingPic_pinanye", imgcover = "ArtGallery/Illustration256/event_yulan_pinanye", imgtext = "平安夜記憶", "0", "0"},
[37] = {sort = 37, itemunlock = 300029, img = "ArtGallery/LoadingPic/LoadingPic_qingrenjie2", imgcover = "ArtGallery/Illustration256/event_yulan_qingrenjie2", imgtext = "情書奪還戰", "0", "0"},
[38] = {sort = 38, itemunlock = 300030, img = "ArtGallery/LoadingPic/LoadingPic_2zhounia", imgcover = "ArtGallery/Illustration256/event_yulan_2zhounian", imgtext = "跨過二十年的約定", "0", "0"},
[39] = {sort = 39, itemunlock = 300031, img = "ArtGallery/LoadingPic/LoadingPic_erzhounian_1", imgcover = "ArtGallery/Illustration256/event_yulan_erzhounian_1", imgtext = "遠古的幽靈", "0", "0"},
[40] = {sort = 40, itemunlock = 300032, img = "ArtGallery/LoadingPic/LoadingPic_erzhounian_2", imgcover = "ArtGallery/Illustration256/event_yulan_erzhounian_2", imgtext = "勇者的登場", "0", "0"},
[41] = {sort = 41, itemunlock = 300033, img = "ArtGallery/LoadingPic/LoadingPic_erzhounian_3", imgcover = "ArtGallery/Illustration256/event_yulan_erzhounian_3", imgtext = "第二城市-新切斯頓", "0", "0"},
[42] = {sort = 42, itemunlock = 300034, img = "ArtGallery/LoadingPic/LoadingPic_erzhounian_4", imgcover = "ArtGallery/Illustration256/event_yulan_erzhounian_4", imgtext = "二十年之別", "0", "0"},
[43] = {sort = 43, itemunlock = 300035, img = "ArtGallery/LoadingPic/LoadingPic_erzhounian_5", imgcover = "ArtGallery/Illustration256/event_yulan_erzhounian_5", imgtext = "遲到二十年的告白", "0", "0"},
[44] = {sort = 44, itemunlock = 300036, img = "ArtGallery/LoadingPic/LoadingPic_erzhounian_6", imgcover = "ArtGallery/Illustration256/event_yulan_erzhounian_6", imgtext = "永別了，勇者", "0", "0"},
[45] = {sort = 45, itemunlock = 300037, img = "ArtGallery/LoadingPic/LoadingPic_modu1", imgcover = "ArtGallery/Illustration256/event_yulan_modu1", imgtext = "山櫻將開的地方", "0", "0"},
[46] = {sort = 46, itemunlock = 300038, img = "ArtGallery/LoadingPic/LoadingPic_xiahuo3", imgcover = "ArtGallery/Illustration256/event_yulan_xiahuo3", imgtext = "宇宙統合光之戰爭", "0", "0"},
[47] = {sort = 47, itemunlock = 390006, img = "ArtGallery/LoadingPic/zjzj_6", imgcover = "ArtGallery/Illustration256/zj_yulan_6", imgtext = "窮途末路", "0", "0"},
[48] = {sort = 48, itemunlock = 300039, img = "ArtGallery/LoadingPic/LoadingPic_2_5zhounian", imgcover = "ArtGallery/Illustration256/event_yulan_2_5zhounian", imgtext = "藏於深處", "0", "0"},
[49] = {sort = 49, itemunlock = 300040, img = "ArtGallery/LoadingPic/LoadingPic_donghuo2", imgcover = "ArtGallery/Illustration256/event_yulan_donghuo2", imgtext = "風雪薄明", "0", "0"},
[50] = {sort = 50, itemunlock = 300041, img = "ArtGallery/LoadingPic/LoadingPic_donghuo2_1", imgcover = "ArtGallery/Illustration256/event_yulan_donghuo2_1", imgtext = "歡迎來到博洛特內", "0", "0"},
[51] = {sort = 51, itemunlock = 300042, img = "ArtGallery/LoadingPic/LoadingPic_donghuo2_2", imgcover = "ArtGallery/Illustration256/event_yulan_donghuo2_2", imgtext = "並不理想的相遇場所", "0", "0"},
[52] = {sort = 52, itemunlock = 300043, img = "ArtGallery/LoadingPic/LoadingPic_donghuo2_3", imgcover = "ArtGallery/Illustration256/event_yulan_donghuo2_3", imgtext = "“篝火”", "0", "0"},
[53] = {sort = 53, itemunlock = 300044, img = "ArtGallery/LoadingPic/LoadingPic_donghuo2_4", imgcover = "ArtGallery/Illustration256/event_yulan_donghuo2_4", imgtext = "無根之人", "0", "0"},
[54] = {sort = 54, itemunlock = 300045, img = "ArtGallery/LoadingPic/LoadingPic_donghuo2_5", imgcover = "ArtGallery/Illustration256/event_yulan_donghuo2_5", imgtext = "最糟的一天", "0", "0"},
[55] = {sort = 55, itemunlock = 300046, img = "ArtGallery/LoadingPic/LoadingPic_donghuo2_6", imgcover = "ArtGallery/Illustration256/event_yulan_donghuo2_6", imgtext = "“投資人”", "0", "0"},
[56] = {sort = 56, itemunlock = 300047, img = "ArtGallery/LoadingPic/LoadingPic_modu2", imgcover = "ArtGallery/Illustration256/event_yulan_modu2", imgtext = "於世界的間隙，亡者將起舞。", "0", "0"},
}
return LoadingimgLocalData
