---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Arno.
--- DateTime: 2026/1/7 10:22
---
require("LocalData/BingoeventLocalData")
require("LocalData/BingopoolLocalData")
require("LocalData/BingoopenLocalData")
local BingoActivityData = require("Model/Activity/ActivityData/BingoActivityData")

-- 硬编码
local Const = {
    [47000] = {
        xLen = 7,
        yLen = 7,
    }
}


---@class BingoViewModel
BingoViewModel = {}

---@private
---@type table<int, BingoActivityData> @ key - activityId
BingoViewModel._activityDataMap = {}
---@private
BingoViewModel._bGotData = false


--region 辅助方法

---@private
---@param activityId int
---@param points NDATA_BingoInfo[]
function BingoViewModel._BuildBingoData(activityId, points)
    local const = Const[activityId]
    if not const then
        Global.LogError("未找到Bingo活动(%s)硬编码配置")
        const = {}
    end
    
    ---@type BingoActivityData
    local actData = BingoActivityData.New(activityId, const)
    actData:PushPoints(points)
    BingoViewModel._activityDataMap[activityId] = actData
end

---@private
---@param activityId int
---@param bNoSure boolean @ 不再返回空对象
---@return BingoActivityData @ 活动不存在或未开启，也会返回空对象
function BingoViewModel._GetBingoData(activityId, bNoSure)
    local actData = BingoViewModel._activityDataMap[activityId]
    if actData then
        return actData
    end
    
    Global.LogError(string.format("Bingo活动(%s)不存在或未开启", activityId))
    if bNoSure then
        return nil
    end
    return BingoActivityData.New(activityId, CheckTable(Const[activityId]))
end

---@private
---@param points NDATA_BingoInfo[]
---@return goods[]
function BingoViewModel._IntegrateRewards(points)
    ---@type goods[]
    local goods = {}

    for _, p in pairs(points) do
        for _, pg in pairs(p.goods) do
            local bNew = true
            
            for _, g in ipairs(goods) do
                if g.goodsID == pg.goodsID and g.goodsType == pg.goodsType then
                    g.goodsNum = g.goodsNum + pg.goodsNum
                    bNew = false
                    break
                end
            end

            if bNew then
                -- 不克隆新表，则会在有重复物品时，道具数量被修改
                table.insert(goods, Copy(pg))
            end
        end
    end
    
    return goods
end

---@private
---@param points NDATA_BingoInfo[]
function BingoViewModel._PreprocessNDATAPoints(points)
    for _, p in pairs(points) do
        p.x = p.x + 1
        p.y = p.y + 1
    end
end

--endregion 辅助方法


--region 用户操作

--- 从后端更新数据
---@param activityId int
---@param onUpdateFinish fun()?
function BingoViewModel.UpdateData(activityId, onUpdateFinish)
    if not activityId or activityId == 0 then
        Global.LogError("传入了空的活动id")
        if onUpdateFinish then
            onUpdateFinish()
        end
        return
    end
    
    local reqData = {
        activityId = activityId,
    }
    BingoViewModel._BingoInfoREQ(reqData, function(tab)
        BingoViewModel._bGotData = true
        
        local points = CheckTable(tab.point)
        BingoViewModel._PreprocessNDATAPoints(points)
        BingoViewModel._BuildBingoData(activityId, points)
        if onUpdateFinish then
            onUpdateFinish()
        end
    end)
end

--- 领取任务奖励
---@param activityId int
---@param taskId int @ nil / 0 表示全部领取
---@param onClaimFinish fun()?
function BingoViewModel.ClaimTask(activityId, taskId, onClaimFinish)
    local actData = BingoViewModel._GetBingoData(activityId, true)
    if not actData then
        if onClaimFinish then
            onClaimFinish()
        end
        return
    end
    
    AchievementViewModel.TaskPerform(TaskControl.DayTaskType.EVENT_RAID, taskId or 0, nil, actData.taskGroupId, function() 
        Event.Go("ActivityDot")
        if onClaimFinish then
            onClaimFinish()
        end
    end)
end

--- 翻牌
---@param activityId int
---@param stage int
---@param x int
---@param y int
---@param onFlipFinish fun(points:NDATA_BingoInfo[], rewards:goods[])? @ points-新打开的格子
function BingoViewModel.FlipCard(activityId, stage, x, y, onFlipFinish)
    if not activityId or activityId == 0 then
        Global.LogError("传入了空的活动id")
        if onFlipFinish then
            onFlipFinish({}, {})
        end
        return
    end
    
    local reqData = {
        activityId = activityId,
        stage = stage,
        -- 需要调整为 0-based
        x = x - 1,
        y = y - 1,
    }
    BingoViewModel._BingoDrawREQ(reqData, function(tab)
        local points = CheckTable(tab.point)
        BingoViewModel._PreprocessNDATAPoints(points)
        
        local actData = BingoViewModel._GetBingoData(activityId, true)
        if actData then
            actData:PushPoints(points)
            
            -- 道具消耗
            local costGoods = actData:GetCostGoods(stage)
            ItemControl.PushSingleItemData(costGoods, ItemControl.PushEnum.consume)
        end

        -- 奖励获取
        local rewards = BingoViewModel._IntegrateRewards(points)
        ItemControl.PushGroupItemData(rewards, ItemControl.PushEnum.add)

        Event.Go("ActivityDot")

        if onFlipFinish then
            onFlipFinish(points, rewards)
        end
    end)
end

--endregion 用户操作


--region 网络操作

---@private
---@param data table
---@param callback fun(tab:table)
function BingoViewModel._BingoInfoREQ(data, callback)
    local bytes = assert(pb.encode("PBClient.ClientBingoInfoReq", data))
    MgrNet.SendReq(MID.CLIENT_BINGO_INFO_REQ, bytes, 0, nil, function(buffer, tag) 
        BingoViewModel._CommonACK("PBClient.ClientBingoInfoAck", MID.CLIENT_BINGO_INFO_REQ, buffer, tag)
    end, function(buffer, tag) 
        local tab = BingoViewModel._CommonNTF("PBClient.ClientBingoInfoNtf", MID.CLIENT_BINGO_INFO_REQ, buffer, tag)
        callback(tab)
    end)
end

---@private
---@param data table
---@param callback fun(tab:table)
function BingoViewModel._BingoDrawREQ(data, callback)
    local bytes = assert(pb.encode("PBClient.ClientBingoDrawReq", data))
    MgrNet.SendReq(MID.CLIENT_BINGO_DRAW_REQ, bytes, 0, nil, function(buffer, tag)
        BingoViewModel._CommonACK("PBClient.ClientBingoDrawAck", MID.CLIENT_BINGO_DRAW_REQ, buffer, tag)
    end, function(buffer, tag)
        local tab = BingoViewModel._CommonNTF("PBClient.ClientBingoDrawNtf", MID.CLIENT_BINGO_DRAW_REQ, buffer, tag)
        callback(tab)
    end)
end

---@private
---@return int
function BingoViewModel._CommonACK(pbKey, reqMid, buffer, tag)
    local tab = assert(pb.decode(pbKey, buffer))
    print(string.format("[ID:%s]errNo:%s", reqMid + 1, tab.errNo))
    if tab.errNo ~= 0 then
        Global.PopTip("Error" .. tab.errNo, 2, true)
    end
    return tab.errNo
end

---@private
---@return table
function BingoViewModel._CommonNTF(pbKey, reqMid, buffer, tag)
    local tab = assert(pb.decode(pbKey, buffer))
    print(string.format("[ID:%s]%s", reqMid + 2, tab))
    print(tab)
    return tab
end

--endregion 网络操作


--region 活动数据

--- 初始化活动数据
--- 主要是为了获取红点数据
--- 只有登录时需要初始化获取，后续活动更新不需要，因为新开启 Bingo 不会自动翻开
function BingoViewModel.InitData()
    --- 遍历所有 Bingo 活动
    for _, config in pairs(BingoeventLocalData.tab) do
        local activityId = CheckNumber(config[2])
        -- 开启的 Bingo 活动，访问后端并初始化数据
        if BingoViewModel.CheckActivityOpen(activityId) then
            BingoViewModel.UpdateData(activityId, function() 
                -- 可能会很晚到达，因此需要触发更新
                Global.LogError(string.format("Bingo活动(%s)数据返回", activityId))
                -- 并非所有红点事件都会自行刷新红点
                BingoViewModel.RefreshAllRedDots()
                Event.Go(EID.BingoDataArrived)
                Event.Go("RedDotFunc")
                Event.Go("ActivityDot")
            end)
        end
    end
end

---@param activityId int
---@return boolean
function BingoViewModel.CheckActivityOpen(activityId)
    local activityData = ActivityControl.GetActivityByID(activityId)
    if not activityData then
        return false
    end

    return (activityData.systemopen == 0 or SysLockControl.CheckSysLock(activityData.systemopen)) and
            (activityData.timeType == 999 or Global.isMiddleTime(activityData.beginTime, activityData.endTime))
end

function BingoViewModel.RefreshAllRedDots()
    local bRedDot = false
    
    --- 有活动数据，只能代表登录游戏时活动是开启的
    for _, actData in pairs(BingoViewModel._activityDataMap) do
        --- 检查活动开启
        if BingoViewModel.CheckActivityOpen(actData.activityId) then
            --- 需要要有未翻开的格子，才检查红点
            if actData:HaveCoveredCell() then
                --- 日常任务
                local dayTaskList = TaskControl.GetEventRaidTaskData(actData.taskGroupId)
                ---@param task DayTaskData
                for _, task in pairs(dayTaskList) do
                    if task.isReceive == 1 then
                        bRedDot = true
                        break
                    end
                end
        
                --- 可翻开
                if not bRedDot then
                    bRedDot = actData:HaveFlippableCell()
                end
        
                --- 目前只有一个 Bingo 活动红点，所以直接跳出
                if bRedDot then
                    break
                end
            end
        end
    end
    
    --- 设置红点（如果要同时开多个 Bingo 活动，则要改到 for 内进行设置）
    local dotData = RedDotControl.GetDotData("Bingo")
    if dotData then
        dotData:SetState(bRedDot)
    else
        Global.LogError("红点数据'Bingo'不存在")
    end
end

---@param activityId int
---@return string @ yyyy/mm/dd/hh:MM-yyyy/mm/dd/hh:MM
function BingoViewModel.GetTimeStr(activityId)
    local activityData = ActivityControl.GetActivityByID(activityId)
    if not activityData then
        Global.LogError(string.format("活动(%s)数据不存在", activityId))
        return ""
    end
    -- 常驻
    if activityData.timeType == 999 then
        return ""
    end
    local bs = string.split(activityData.beginTime, "-")
    local es = string.split(activityData.endTime, "-")
    return string.format("%s/%s/%s/%s:%s-%s/%s/%s/%s:%s",
            bs[1], bs[2], bs[3], bs[4], bs[4],
            es[1], es[2], es[3], es[4], es[5])
end

--endregion 活动数据


--region Bingo数据

--- 是否获取到了数据
---@return boolean
function BingoViewModel.HaveData()
    return BingoViewModel._bGotData
end

--- 获得 Bingo 网格边长
---@param activityId int
---@return int, int @ xLen, yLen
function BingoViewModel.GetBingoGridLen(activityId)
    local actData = BingoViewModel._GetBingoData(activityId)
    return actData.xLen, actData.yLen
end

---@param activityId int
---@param stage int
---@return goods @ 非源数据，goodsNum 是所需
function BingoViewModel.GetBingoCost(activityId, stage)
    return BingoViewModel._GetBingoData(activityId):GetCostGoods(stage)
end

---@param activityId int
---@return int
function BingoViewModel.GetBingoCurrentStage(activityId)
    return BingoViewModel._GetBingoData(activityId):GetCurrentStage()
end

---@param activityId int
---@return int
function BingoViewModel.GetBingoMaxStage(activityId)
    return BingoViewModel._GetBingoData(activityId).maxStage
end

--- 获取格子数据
---@param activityId int
---@param stage int @ 阶段
---@param x int
---@param y int
---@return BingoCellData @ 非源数据
function BingoViewModel.GetBingoCell(activityId, stage, x, y)
    return  BingoViewModel._GetBingoData(activityId):GetCellData(stage, x, y)
end

---@param activityId int
---@return BingoTaskData[] @ 非源数据
function BingoViewModel.GetBingoTasks(activityId)
    return BingoViewModel._GetBingoData(activityId):GetBingoTaskList()
end

--endregion Bingo数据

function BingoViewModel.Clear()
    BingoViewModel._activityDataMap = {}
    BingoViewModel._bGotData = false
end

return BingoViewModel
