---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Arno.
--- DateTime: 2026/3/13 18:03
---

--- 提供一些通用的 UI 方法
---@class CommonViewModel
CommonViewModel = {}

--region 通用方法

---@generic T
---@class CommonWeightData
---@field weight int
---@field data T @ 可自定义内容

---@generic T
---@param weightDataList CommonWeightData[] @ <T>
---@param totalWeight int? @ 空则通过 weightDataList 计算
---@return T, int @ data, index
function CommonViewModel.GetRandomWeightData(weightDataList, totalWeight)
    if not weightDataList or #weightDataList == 0 then
        return nil, 0
    end

    if not totalWeight then
        totalWeight = 0
        for _, wData in ipairs(weightDataList) do
            totalWeight = totalWeight + wData.weight
        end
    end
    
    local randomNum = math.random(0, totalWeight)
    local curWeight = 0
    for i, wData in ipairs(weightDataList) do
        curWeight = curWeight + wData.weight
        if randomNum <= curWeight then
            return wData.data, i
        end
    end
    
    Global.LogError("Weight data wrong. Return first data.")
    return weightDataList[1].data, 1
end

--- 从容器中选出部分值
---@generic TData
---@param container TData[]
---@param fSelector fun(data:TData):boolean
---@return TData[]
function CommonViewModel.FSelect(container, fSelector)
    local list = {}
    for _, data in pairs(container) do
        if fSelector(data) then
            table.insert(list, data)
        end
    end
    return list
end

--endregion 通用方法

--region 常见UI逻辑

--- 通用的返回相关按钮逻辑
---@param uid int @ 界面 uid
---@param backBtn UnityEngine.GameObject?
---@param homeBtn UnityEngine.GameObject?
---@param helpBtn UnityEngine.GameObject?
---@param tutorialId int? @ 帮助按钮显示内容
function CommonViewModel.CommonReturnBtns(backBtn, homeBtn, helpBtn, tutorialId)
    if not Global.IsNil(backBtn) then
        UIEvent.LuaClick(backBtn, function()
            MgrUI.GoBack()
        end)
    end

    if not Global.IsNil(homeBtn) then
        UIEvent.LuaClick(homeBtn, function() 
            MgrUI.GoBackTo(UID.Home_UI)
        end)
    end

    if not Global.IsNil(helpBtn) then
        UIEvent.LuaClick(helpBtn, function()
            if tutorialId and tutorialId ~= 0 then
                ActiveTutorialControl.OpenGuide(tutorialId)
            else
                Global.PopTip("Click help", nil, true)
            end
        end)
    end
end

--- 通用的返回事件方法
---@param uid int @ 界面uid
function CommonViewModel.CommonBackKey(uid)
    if MgrUI.IsPopOpen() or not MgrUI.IsShow(uid) then
        return
    end
    MgrUI.GoBack()
end

--endregion 常见UI逻辑

--region 角色相关
--- 由于 PosterGirlViewModel 明显是与首页看板娘高度相关的内容，且较为复杂，不想进行修改。
--- 因此将后续界面所需角色相关方法置于此，可能也会用到 PosterGirlViewModel 内的方法。
--- 关于 npcId: 该值通常为 Storyactivity 表npc字段配置。其并不一定和 roleId 一一对应，同一个 role 可能有多个 npcId.

--- 读取类型，ActorLinesLocalData[3]
--- 由于数量过多，在需要时进行补齐
---@alias ActorLinesReadType int
CommonViewModel.ActorLinesReadType = {
    TOUCH = 5,
    DRESSED_IDLE = 91,
    DRESSED_TOUCH = 92,
    UNDRESSING = 93,
    UNDRESSED_IDLE = 94,
    UNDRESSED_TOUCH = 95,
    DRESSING = 96,
    ACTIVITY_SHOP_NORMAL = 97,
    ACTIVITY_SHOP_EXCHANGE = 98,
}

--- 交互类型，ActorLinesLocalData[4]
--- 由于数量过多，在需要时进行补齐
---@alias ActorLinesType int
CommonViewModel.ActorLinesType = {
    TOUCH = 5,
}

--- 触发条件，ActorLinesLocalData[5]
--- 由于数量过多，在需要时进行补齐
---@alias ActorLinesCondition int
CommonViewModel.ActorLinesCondition = {
    ROLE_FAVOR = 1,    -- 角色好感度
    CG_STATUS = 14,    -- CG状态人物语音(14_[点击区域id])
    TOUCH_AREA = 15,   -- 点击区域控制触发动作(15_[点击区域id])
}

---@type table<int, table[]> @ key - group, value - ActorLinesLocalData[]
local ActorLinesGroupMap = {}

--- TODO(Arno) 未经过验证
--- 在指定 Root 下创建 NpcSpine
---@param npcId int @ 用于Charactercoordinates表确定坐标及加载角色预制体。
---@param spineRoot UnityEngine.GameObject
---@param callback fun(spineObj:UnityEngine.GameObject)
function CommonViewModel.CreateNpcSpine(npcId, spineRoot, callback)
    if npcId == 0 then
        return
    end
    if Global.IsNil(spineRoot) then
        Global.LogError("Create npc spine failed. SpineRoot does not exist.")
        return
    end
    
    local coordStr = CheckTable(CharactercoordinatesLocalData.tab[npcId]).coordinate10
    local x = 0
    local y = 0
    local scale = 1
    if not Global.IsStrNil(coordStr) then
        local splitStr1 = string.split(coordStr, ";")
        local splitStr2 = string.split(splitStr1[1], ",")
        x = tonumber(splitStr2[1]) or 0
        y = tonumber(splitStr2[2]) or 0
        scale = tonumber(splitStr1[2]) or 1
        --local turn = tonumber(splitStr1[3])
    end
    ---@param obj UnityEngine.GameObject
    MgrRes.LoadWatch3DSpineInUI(spineRoot, npcId, x, y, scale, "idle", function(obj)
        -- UI 层
        obj.layer = 5
        if callback then
            callback(obj)
        end
    end)
end

--- TODO(Arno) 未经过验证
--- 播放 npc 语音
---@param npcId int @ 用于ActorLines表检索group
---@param readType ActorLinesReadType @ 用于ActorLines表检索readType
---@param spineObj UnityEngine.GameObject @ 播放角色语音动画
---@param txtComp TMPro.TextMeshProUGUI @ 显示语音台词
---@param wordRoot UnityEngine.GameObject @ 显示台词时显隐，空则为 txtComp 对象
---@param timerName string? @ 监听结束计时器，空则不开启计时器。通过 MgrTimer.Cancel 取消
---@param fOnVoiceEnd fun()? @ 监听到语音结束时的回调。空则执行默认的逻辑——隐藏 wordRoot。该方法内不需要手动取消监听。
function CommonViewModel.PlayNpcVoice(npcId, readType, spineObj, txtComp, wordRoot, timerName, fOnVoiceEnd)
    local lineId = CommonViewModel.GetRandomActionLine(npcId, readType)
    local lData = ActorVoiceLocalData.tab[CheckNumber(lineId)]
    if not lData then
        return
    end
    
    local animationName = lData[6]
    local audioName = lData[13]
    local content = lData[7]

    if not Global.IsConfigNil(animationName) and not Global.IsNil(spineObj) then
        CMgrSpine.Instance:SetSpineAnimation(spineObj, animationName, true)
    end
    if not Global.IsConfigNil(content) and not Global.IsNil(txtComp) then
        if Global.IsNil(wordRoot) then
            wordRoot = txtComp.gameObject
        end
        txtComp.text = content
        wordRoot:SetActive(true)
    end
    
    if not Global.IsConfigNil(audioName) then
        local npcIdStr = tostring(npcId)
        MgrSound.PlayRole(audioName, nil, nil, false, 0, 0, npcIdStr)
        if not Global.IsStrNil(timerName) then
            MgrTimer.AddRepeat(timerName, 0.2, function()
                if not MgrSound.CheckRoleStatus(npcIdStr) then
                    return
                end
                MgrTimer.Cancel(timerName)
                if fOnVoiceEnd then
                    fOnVoiceEnd()
                else
                    if not Global.IsNil(wordRoot) then
                        wordRoot:SetActive(false)
                    end
                end
            end, -1, nil)
        end
    end
end

-- TODO(Arno) 待优化
--- 获取 Npc 某类台词列表
---@param npcId int @ 用于ActorLines表检索group
---@param readType ActorLinesReadType @ 用于ActorLines表检索readType
---@return CommonWeightData[], int @ data为台词id, 总权重
function CommonViewModel.GetNpcActorLines(npcId, readType)
    ---@type CommonWeightData[]
    local list = {}
    local totalWeight = 0
    
    -- TODO(Arno) 每次都搜一万多行数据？考虑是否需要缓存为字典
    for id, line in pairs(ActorLinesLocalData.tab) do
        if line[2] == npcId and line[3] == readType then
            -- TODO(Arno) 暂不考虑条件，若要添加，见 TableToObject.GetTargetWeight
            ---@type CommonWeightData<int>
            local wData = {
                -- 固定值
                weight = 10,
                data = id,
            }
            totalWeight = totalWeight + wData.weight
            table.insert(list, wData)
        end
    end
    
    return list, totalWeight
end

-- TODO(Arno) 待优化
---@param npcId int @ 用于ActorLines表检索group
---@param readType ActorLinesReadType @ 用于ActorLines表检索readType
---@return int @ ActorLines.id
function CommonViewModel.GetRandomActionLine(npcId, readType)
    local wDataList, totalWeight = CommonViewModel.GetNpcActorLines(npcId, readType)
    local lineId, _ = CommonViewModel.GetRandomWeightData(wDataList, totalWeight)
    return lineId or 0
end

--- 返回源数据，请勿修改
--- key 只是顺序插入的索引，无意义
---@param group
---@return table[] @ ActorLinesLocalData[]
function CommonViewModel.GetActorLinesByGroup(group)
    local list = ActorLinesGroupMap[group]
    if list then
        return list
    end

    list = CommonViewModel.FSelect(ActorLinesLocalData.tab, function(data)
        return data[2] == group
    end)
    ActorLinesGroupMap[group] = list
    return list
end

--endregion 角色相关

function CommonViewModel.Clear()
    ActorLinesGroupMap = {}
end

return CommonViewModel
