---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Arno.
--- DateTime: 2025/8/19 11:06
---
require("LocalData/TaskVoidShopLocalData")

--region DataDefine
---@class CumulativeSalesCoinData : goods
---@field goodsIcon string
---@field jumpStr string

---@class CumulativeSalesWeightData
---@field weight int
---@field data any @ data 可自行定义内容

---@class CumulativeSalesActivityData
---@field activityId int
---@field taskGroupIds int[] @ 匹配任务表的 activeid
---@field taskGroupNames string[]
---@field dayTaskGroupId int
---@field dayTaskGroupName string
---@field shopType int

--- 不知道为什么成就任务还要分多个列表存储，考虑到效率，这里要缓存一下基本数据
---@class CumulativeSalesAchievementTaskData
---@field taskId int
---@field taskType TaskControl.AchievementTaskType
--endregion DataDefine


---@class CumulativeSalesViewModel
CumulativeSalesViewModel = {}

--- 累销活动支持的任务类型
---@alias CumulativeSalesViewModel.TaskTypeEnum int
CumulativeSalesViewModel.TaskTypeEnum = {
    ACHIEVEMENT = 0,
    DAILY = 1,  -- 对应 TaskControl.DayTaskType.EVENT_RAID
}

--- 由活动界面打开商店界面时传递的参数
---@type any
local shopFormArgs
---@type table<int, table<int, CumulativeSalesWeightData[]>> @ [roleId, [readType, table]]
local cacheActorLinesMap = {}
---@type table<int, CumulativeSalesAchievementTaskData[]> @ [taskGroupId, data[]]
local cacheAchievementTaskDataMap = {}

--region 参数传递
---@param args any
function CumulativeSalesViewModel.SetShopFormArgs(args)
    shopFormArgs = args
end

---@return any
function CumulativeSalesViewModel.GetShopFormArgs()
    return shopFormArgs
end
--endregion 参数传递

--region 数据操作
---@param activityId int
---@return CumulativeSalesActivityData | nil
function CumulativeSalesViewModel.GetCumulativeSalesActivityData(activityId)
    for id, tab in pairs(TaskVoidShopLocalData.tab) do
        if tab[2] == activityId then
            local taskGroupIdsSplit = string.split(tab[4], ",")
            ---@type CumulativeSalesActivityData
            local data = {
                activityId = tab[2],
                taskGroupIds = {},
                taskGroupNames = string.split(tab[7], ","),
                dayTaskGroupId = tab[6] or 0,
                dayTaskGroupName = tab[8],
                shopType = tonumber(tab[5]) or 0,
            }
            for _, taskGroupIdStr in ipairs(taskGroupIdsSplit) do
                table.insert(data.taskGroupIds, tonumber(taskGroupIdStr))
            end
            return data
        end
    end
    return nil
end

--- 用当前背包内道具数量更新 goods 字段
---@param goods goods
function CumulativeSalesViewModel.RefreshGoodsNum(goods)
    local item = ItemControl.GetItemByIdAndType(goods.goodsID, goods.goodsType)
    goods.goodsNum = item.count
end
--endregion 数据操作

--region 红点
--- 目前仅有一种注册红点，后续新增则要修改该方法
function CumulativeSalesViewModel.RefreshAllRedDots()
    ---@return boolean
    local CheckTaskRedDot = function(taskType, taskGroupId) 
        local taskList = CumulativeSalesViewModel.GetTaskList(taskType, taskGroupId)
        for _, task in ipairs(taskList) do
            if task.isReceive == 1 then
                return true
            end
        end
        return false
    end
    
    
    for _, tab in pairs(TaskVoidShopLocalData.tab) do
        local activityId = tab[2]
        local activityData = ActivityControl.GetActivityByID(activityId)
        local bRedDot = false
        -- 活动开启
        local bOpen = false
        if activityData then
            if activityData.timeType == 999 or  
                Global.isMiddleTime(activityData.beginTime, activityData.endTime) then
                bOpen = true
            end
        end
        if bOpen then
            --- 日常任务
            local taskGroupId = tab[6]
            if CheckTaskRedDot(CumulativeSalesViewModel.TaskTypeEnum.DAILY, taskGroupId) then
                bRedDot = true
            end

            --- 成就任务
            if not bRedDot then
                local taskGroupIdsSplit = string.split(tab[4], ",")
                for _, idStr in ipairs(taskGroupIdsSplit) do
                    local id = tonumber(idStr)
                    if CheckTaskRedDot(CumulativeSalesViewModel.TaskTypeEnum.ACHIEVEMENT, id) then
                        bRedDot = true
                        break
                    end
                end
            end

            -- 目前累销活动会同时存在两种，要特别处理
            if activityId == ActivityControl.activityTypeEnum.CUMULATIVE_SALES * 100 + 1 then
                ---@type RedDotData
                local dotData = RedDotControl.GetDotData("CumulativeSales2")
                dotData:SetState(bRedDot)
            else
                ---@type RedDotData
                local dotData = RedDotControl.GetDotData("CumulativeSales")
                dotData:SetState(bRedDot)
            end
        end
    end
end
--endregion 红点

--region 任务
---@param taskType CumulativeSalesViewModel.TaskTypeEnum
---@param taskGroupId int
---@param bSorted boolean
---@return AchievementTaskData[] | DayTaskData[]
function CumulativeSalesViewModel.GetTaskList(taskType, taskGroupId, bSorted)
    if taskType == CumulativeSalesViewModel.TaskTypeEnum.ACHIEVEMENT then
        return CumulativeSalesViewModel.GetAchievementTaskList(taskGroupId, bSorted)
    elseif taskType == CumulativeSalesViewModel.TaskTypeEnum.DAILY then
        return CumulativeSalesViewModel.GetDayTaskList(taskGroupId, bSorted)
    end
    return {}
end

---@param taskType CumulativeSalesViewModel.TaskTypeEnum
---@param taskId int
---@param selfTaskType TaskControl.AchievementTaskType | TaskControl.DayTaskType
---@return int, int @ currentProgress, maxProgress
function CumulativeSalesViewModel.GetTaskProgress(taskType, taskId, selfTaskType)
    if taskType == CumulativeSalesViewModel.TaskTypeEnum.ACHIEVEMENT then
        return CumulativeSalesViewModel.GetAchievementTaskProgress(taskId, selfTaskType)
    elseif taskType == CumulativeSalesViewModel.TaskTypeEnum.DAILY then
        return CumulativeSalesViewModel.GetDayTaskProgress(taskId)
    end
    return 0
end

---@param taskType CumulativeSalesViewModel.TaskTypeEnum
---@param taskGroupId int @ 该值是在一键领取时需要的
---@param taskId int? @ default 0，0-全部领取
---@param callback fun()?
function CumulativeSalesViewModel.PerformTask(taskType, taskGroupId, taskId, callback)
    if taskType == CumulativeSalesViewModel.TaskTypeEnum.ACHIEVEMENT then
        CumulativeSalesViewModel.PerformAchievementTask(taskGroupId, taskId, callback)
    elseif taskType == CumulativeSalesViewModel.TaskTypeEnum.DAILY then
        CumulativeSalesViewModel.PerformDayTask(taskGroupId, taskId, callback)
    end
end

---@param taskGroupId int
---@param bSorted boolean
---@return AchievementTaskData[]
function CumulativeSalesViewModel.GetAchievementTaskList(taskGroupId, bSorted)
    if not cacheAchievementTaskDataMap[taskGroupId] then
        ---@type CumulativeSalesAchievementTaskData[]
        local list = {}
        for id, tab in pairs(ActiveLocalData.tab) do
            local activeId = tab[16]
            if activeId == taskGroupId then
                ---@type CumulativeSalesAchievementTaskData
                local data = {
                    taskId = id,
                    taskType = tab[2],
                }
                table.insert(list, data)
            end
        end
        cacheAchievementTaskDataMap[taskGroupId] = list
    end
    ---@type AchievementTaskData[]
    local taskList = {}
    --- 不知道为什么成就任务要分多个列表存储，因此这里得从多个列表获取
    for _, data in ipairs(cacheAchievementTaskDataMap[taskGroupId]) do
        ---@type AchievementTaskData
        local taskData = CumulativeSalesViewModel.GetAchievementTaskData(data.taskId, data.taskType)
        if taskData then
            table.insert(taskList, taskData)
        end
    end
    if bSorted then
        CumulativeSalesViewModel.SortTaskList(taskList)
    end
    return taskList
end

---@param taskId int
---@param taskType TaskControl.AchievementTaskType
---@return int, int @ currentProgress, maxProgress
function CumulativeSalesViewModel.GetAchievementTaskProgress(taskId, taskType)
    local taskData = CumulativeSalesViewModel.GetAchievementTaskData(taskId, taskType)
    if not taskData then
        return 0
    end
    local completeStr = string.split(taskData.complete, "_")
    local statisticId = tonumber(completeStr[1]) or 0
    return TaskControl.gloryStatistics[statisticId] or 0, tonumber(completeStr[3]) or 1
end

---@param taskGroupId int
---@param taskId int? @ default 0，0-全部领取
---@param callback fun()?
function CumulativeSalesViewModel.PerformAchievementTask(taskGroupId, taskId, callback)
    AchievementViewModel.TaskPerform(0, taskId or 0, nil, taskGroupId, function() 
        Event.Go("ActivityDot")
        if callback then
            callback()
        end
    end)
end

---@param taskGroupId int
---@param bSorted boolean
---@return DayTaskData[]
function CumulativeSalesViewModel.GetDayTaskList(taskGroupId, bSorted)
    local taskList = TaskControl.GetEventRaidTaskData(taskGroupId)
    if bSorted then
        CumulativeSalesViewModel.SortTaskList(taskList)
    end
    return taskList
end

---@param taskId int
---@return int, int @ currentProgress, maxProgress
function CumulativeSalesViewModel.GetDayTaskProgress(taskId)
    local taskData = TaskControl.EventRaidTaskDataList[taskId]
    if not taskData then
        return 0
    end
    local completeStr = string.split(taskData.complete, "_")
    local statisticId = tonumber(completeStr[1]) or 0
    local maxProgress = tonumber(completeStr[3]) or 1
    local progress = 0
    -- 每日登录这种好像不会有统计数据
    if taskData.isReceive == 1 or taskData.isComplete == 1 then
        progress = maxProgress
    else
        progress = TaskControl.EventRaidStatistics[statisticId] or 0
    end
    return progress, maxProgress
end

---@param taskGroupId int
---@param taskId int? @ default 0，0-全部领取
---@param callback fun()?
function CumulativeSalesViewModel.PerformDayTask(taskGroupId, taskId, callback)
    AchievementViewModel.TaskPerform(TaskControl.DayTaskType.EVENT_RAID, taskId or 0, nil, taskGroupId, function()
        Event.Go("ActivityDot")
        if callback then
            callback()
        end
    end)
end
--endregion 任务

--region 商店
--- 获得商店要显示的货币列表
---@param shopType int
---@param outCoinList CumulativeSalesCoinData[]? @ 
---@return CumulativeSalesCoinData[]
function CumulativeSalesViewModel.GetShopCoinList(shopType, outCoinList)
    outCoinList = outCoinList or {}
    local shopData = ShoptypeLocalData.tab[shopType]
    if not shopData then
        return outCoinList
    end
    local coinSplit1 = string.split(shopData.icons, ";")
    for _, str1 in ipairs(coinSplit1) do
        local coinSplit2 = string.split(str1, ",")
        local coinStr = coinSplit2[1]
        local jumpStr = coinSplit2[2]
        local coins = string.split(coinStr, "_")
        local coinType = tonumber(coins[1])
        local coinId = tonumber(coins[2])
        local coinItem = ItemControl.GetItemByIdAndType(coinId, coinType)
        ---@type CumulativeSalesCoinData
        local costData = {
            goodsType = coinType,
            goodsID = coinId,
            goodsNum = coinItem.count,
            goodsIcon = coinItem.icon,
            jumpStr = jumpStr,
        }
        table.insert(outCoinList, costData)
    end
    return outCoinList
end

--- 获得商店的商品列表
---@param shopType int
---@field outShopItemList ShopItemData[]?
---@return ShopItemData[]
function CumulativeSalesViewModel.GetShopItemList(shopType, outShopItemList)
    outShopItemList = outShopItemList or {}
    local shopItems = ShopControl.GetCertainTypeShopData(shopType)
    if not shopItems then
        return outShopItemList
    end
    for _, shopItem in pairs(shopItems) do
        table.insert(outShopItemList, shopItem)
    end
    ---@param a ShopItemData
    ---@param b ShopItemData
    table.sort(outShopItemList, function(a, b)
        if a.sortIdx == b.sortIdx then
            return a.id < b.id
        end
        return a.sortIdx < b.sortIdx
    end)
    return outShopItemList
end

--- 检查商品是否锁定
---@param shopItem ShopItemData
---@param bPopTip boolean
---@return boolean
function CumulativeSalesViewModel.CheckShopItemLock(shopItem, bPopTip)
    local sysId = shopItem.buyLimit
    if sysId == 0 then
        return false
    end
    if SysLockControl.CheckSysLock(sysId) then
        return false
    end
    if bPopTip then
        Global.PopTip(SysLockControl.GetSystemLockTips(sysId), nil, true)
    end
    return true
end

--- 弹出购买界面，用户选择购买数量后购买
---@param shopItem ShopItemData
---@param callback fun(count:int)
function CumulativeSalesViewModel.BuyShopItem(shopItem, callback)
    local priceGoods = shopItem:GetPrice()
    local priceItem = ItemControl.GetItemByIdAndType(priceGoods.goodsID, priceGoods.goodsType)
    local bInfinite = shopItem.buyMaxCount == 0
    local restCount = bInfinite and 99 or shopItem.buyMaxCount - shopItem.buyCount
    local canBuyCount = math.floor(priceItem.count / priceGoods.goodsNum)
    MgrUI.Pop(UID.BuyPop_UI, {
        shopItem,
        function(count)
            -- 选择购买数量超过可买数量
            if count > canBuyCount then
                Global.PopTip(string.format(
                        MgrLanguageData.GetLanguageByKey("shop_ui_buyfail1"),
                        priceItem.name),
                        nil, true)
                return
            end
            -- 走购买接口
            ShopViewModel.SendBuyGoods({ shopItem.id, count}, function()
                if callback then
                    callback(count)
                end
            end)
        end,
        1,
        restCount,
        true,
        canBuyCount,
        nil,
    }, true)
end
--endregion 商店

--region 看板娘
--- 创建看板娘 Spine
---@param roleId int @ 0 则无行为
---@param spineRoot UnityEngine.GameObject | UnityEngine.MonoBehaviour
---@param shopType int
---@param callback fun(spineGo:UnityEngine.GameObject) @ 异步创建完成后触发
function CumulativeSalesViewModel.CreatePosterGirlSpine(roleId, spineRoot, shopType, callback)
    if roleId == 0 then
        return
    end
    local coordStr = CharactercoordinatesLocalData.tab[roleId].coordinate10
    local x = 0
    local y = 0
    local scale = 1
    if not Global.IsStrNil(coordStr) then
        local splitStr1 = string.split(coordStr, ";")
        local splitStr2 = string.split(splitStr1[1], ",")
        x = tonumber(splitStr2[1]) or 0
        y = tonumber(splitStr2[2]) or 0
        scale = tonumber(splitStr1[2]) or 1
        --local turn = tonumber(splitStr1[3])
    end
    --MgrRes.LoadWatchAuto(spineRoot, roleId, x, y, scale, "idle", callback)
    ---@param obj UnityEngine.GameObject
    MgrRes.LoadWatch3DSpineInUI(spineRoot, roleId, x, y, scale, "idle", function(obj)
        -- UI 层
        obj.layer = 5
        if callback then
            callback(obj)
        end
    end)
end

--- 获得角色随机台词id
---@param roleId int @ 0 则无行为
---@param readType int
---@return int @ 0 表示无
function CumulativeSalesViewModel.GetRandomActorLinesId(roleId, readType)
    if roleId == 0 then
        return 0
    end
    if not cacheActorLinesMap[roleId] then
        cacheActorLinesMap[roleId] = {}
    end
    if not cacheActorLinesMap[roleId][readType] then
        cacheActorLinesMap[roleId][readType] = CumulativeSalesViewModel.BuildActorLinesWeightMap(roleId, readType)
    end
    local _, linesId = CumulativeSalesViewModel.GetWeightRandomData(cacheActorLinesMap[roleId][readType])
    return linesId or 0
end

--- 获取角色台词内容
---@param actorLineId int @ 0 表示无
---@return string | nil, string | nil, string | nil @ 台词内容，动画名称，语音文件名
function CumulativeSalesViewModel.GetActorLinesContent(actorLineId)
    if not actorLineId or actorLineId == 0 then
        return nil
    end
    local tab = ActorLinesLocalData.tab[actorLineId]
    if not tab then
        return nil
    end
    local aniName = tab[6]
    local content = tab[7]
    local audioName = tab[13]
    return content, aniName, audioName
end

--- 构建角色台词权重字典，不考虑解锁条件
---@param roleId int
---@param readType int
---@param outLinesMap CumulativeSalesWeightData[]?
---@return CumulativeSalesWeightData[] @ data = lineId
function CumulativeSalesViewModel.BuildActorLinesWeightMap(roleId, readType, outLinesMap)
    outLinesMap = outLinesMap or {}
    for _, tab in pairs(ActorLinesLocalData.tab) do
        if tab[2] == roleId and tab[5] == "0" and tab[3] == readType then
            ---@type CumulativeSalesWeightData
            local wData = {
                -- 当前没有权重值设置，固定为 10
                weight = 10,
                data = tab[1],
            }
            table.insert(outLinesMap, wData)
        end
    end
    return outLinesMap
end
--endregion 看板娘

--region 时间
--- 将 Y-m-d-H-M-S 转换为 Y/m/d H:M
--- 若传入 endTimeStr 则为 [...] - [...]
---@param timeStr string
---@param endTimeStr string
---@return string
function CumulativeSalesViewModel.TimeStrConvert01(timeStr, endTimeStr)
    if Global.IsStrNil(timeStr) then
        return ""
    end
    local str1 = string.split(timeStr, "-")
    if Global.IsStrNil(endTimeStr) then
        return string.format("%s/%s/%s %s:%s", str1[1], str1[2], str1[3], str1[4], str1[5])
    end
    local str2 = string.split(endTimeStr, "-")
    return string.format("%s/%s/%s %s:%s - %s/%s/%s %s:%s",
        str1[1], str1[2], str1[3], str1[4], str1[5],
        str2[1], str2[2], str2[3], str2[4], str2[5])
end
--endregion 时间

--region 通用功能
--- 获取权重随机数据
---@param weightDataList CumulativeSalesWeightData[] @ 要求权重为独立值
---@return int, any @ index, data
function CumulativeSalesViewModel.GetWeightRandomData(weightDataList)
    if not weightDataList or #weightDataList == 0 then
        return 0, nil
    end
    
    local maxWeight = 0
    for _, wData in ipairs(weightDataList) do
        maxWeight = maxWeight + wData.weight
    end
    local randomNum = math.random(0, maxWeight)
    local curWeight = 0
    for i, wData in ipairs(weightDataList) do
        curWeight = curWeight + wData.weight
        if randomNum <= curWeight then
            return i, wData.data
        end
    end
    print("权重随机错误，返回第一个数据")
    return 1, weightDataList[1].data
end

--- 通用任务排序：可领取->未完成->已完成 (id升序)
---@param taskList AchievementTaskData[] | DayTaskData[]
function CumulativeSalesViewModel.SortTaskList(taskList)
    ---@param a AchievementTaskData | DayTaskData
    ---@param b AchievementTaskData | DayTaskData
    table.sort(taskList, function(a, b)
        if a.isReceive == b.isReceive then
            if a.isComplete == b.isComplete then
                return a.id < b.id
            else
                return a.isComplete < b.isComplete
            end
        else
            return a.isReceive > b.isReceive
        end
    end)
end

---@param taskId int
---@param taskType TaskControl.AchievementTaskType
---@return AchievementTaskData | nil
function CumulativeSalesViewModel.GetAchievementTaskData(taskId, taskType)
    ---@type AchievementTaskData
    local taskData
    if taskType == TaskControl.AchievementTaskType.NOVICE then
        taskData = TaskControl.NoviceDataList[taskId]
    elseif taskType == TaskControl.AchievementTaskType.GUIDE then
        taskData = TaskControl.GuideDataList[taskId]
    else
        taskData = TaskControl.AchievementDataList[taskId]
    end
    if not taskData then
        return nil
    end
    taskData.isComplete = TaskControl.CheckComplete(taskData.id) and 1 or 0
    taskData.isReceive = TaskControl.CheckAchieveReceived(taskData) and 1 or 0
    if taskData.isComplete == 1 or TaskControl.CheckTaskLock(taskData) then
        return taskData
    end
    return nil
end
--endregion 通用功能

function CumulativeSalesViewModel.Clear()
    shopFormArgs = nil
    -- cache 仅是配表缓存，目前来看没必要清空
    --cacheActorLinesMap = {}
    --cacheAchievementTaskDataMap = {}
end

return CumulativeSalesViewModel
