---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Arno.
--- DateTime: 2026/1/14 11:33
---

--region 数据定义
---@class BingoTaskData
---@field taskId int
---@field content string
---@field progress int
---@field maxProgress int
---@field state int @ 0-未完成，1-已完成，2-已领取
---@field rewards goods[]

---@class NDATA_BingoInfo
---@field stage int
---@field x int @ 后端发送过来是 0-based，不过会统一处理为 1-based
---@field y int
---@field goods goods[]

---@class BingoStageData
---@field costGoods goods
---@field flippedGrid BingoCellData[][] @ y, x。会存在空洞，只记录已经翻开的。
---@field flippedCount int

---@class BingoCellData
---@field bFlipped boolean
---@field goods goods? @ 未翻开的可能没有物品信息
--endregion 数据定义

--region BingoStageData
---@param config table? @ BingopoolLocalData. 支持空，以创建"不正确"的对象
---@return BingoStageData
local function _StageData_Build(config)
    ---@type BingoStageData
    local data = {
        flippedGrid = {},
        flippedCount = 0,
    }

    if config then
        local useItemStrArr = string.split(config[4], "_")
        data.costGoods = {
            goodsType = CheckNumber(useItemStrArr[1]),
            goodsID = CheckNumber(useItemStrArr[2]),
            goodsNum = CheckNumber(useItemStrArr[3]),
        }
    else
        data.costGoods = {}
    end

    return data
end

---@param data BingoStageData
---@param x int
---@param y int
---@return BingoCellData | nil
local function _StageData_Get(data, x, y)
    local row = data[y]
    if not row then return nil end
    return row[x]
end

---@param data BingoStageData
---@param point NDATA_BingoInfo
---@return BingoCellData
local function _StageData_Push(data, point) 
    local x = point.x
    local y = point.y
    
    data.flippedCount = data.flippedCount + 1
    
    local row = data[y]
    if not row then
        row = {}
        data[y] = row
    end

    ---@type BingoCellData
    local cell = {
        bFlipped = true,
        goods = CheckTable(point.goods)[1],
    }

    if row[x] and row[x].bFlipped then
        Global.LogError(string.format("Bingo活动阶段%s格子[%s,%s]重复翻开", point.stage, x, y))
    end
    row[x] = cell
    
    return cell
end
--endregion BingoStageData


---@class BingoActivityData
---@field activityId int
---@field taskGroupId int
---@field xLen int
---@field yLen int
---@field maxStage int
local BingoActivityData = Class("BingoActivityData")

---@param activityId int
---@param constTab table @ 约定的一些硬编码数据
function BingoActivityData:ctor(activityId, constTab)
    self.activityId = activityId
    self.taskGroupId = 0
    self.xLen = constTab.xLen or 7
    self.yLen = constTab.yLen or 7
    self.maxStage = 1
    
    ---@protected 升阶所需翻牌数量
    self._upgradeNum = self.yLen * self.xLen
    ---@protected
    self._currentStage = 1
    ---@protected
    self._stages = {}
    
    self:_InitStages()
    self:_InitTask()
end

---@param points NDATA_BingoInfo[]
function BingoActivityData:PushPoints(points)
    for _, p in pairs(points) do
        local stage = p.stage
        local stgData = self._stages[stage]
        if not stgData then
            stgData = _StageData_Build()
            self._stages[stage] = stgData
            Global.LogError(string.format("Bingo活动(%s)阶段%s配置不存在", self.activityId, stage))
        end
        
        _StageData_Push(stgData, p)
    end
    
    self:_CalcCurrentStage()
end

--- 获取当前解锁到的阶段
---@return int
function BingoActivityData:GetCurrentStage()
    return self._currentStage
end

---@param stage int
---@param bBackpack boolean @ goodsNum: true-背包数量, false-所需数量
---@return goods @ 非源数据
function BingoActivityData:GetCostGoods(stage, bBackpack)
    local stgData = self:_GetStageData(stage)
    if not stgData then
        return {}
    end
    
    local costGoods = stgData.costGoods
    
    if not bBackpack then
        return clone(costGoods)
    end
    
    local costItem = ItemControl.GetItemByIdAndType(costGoods.goodsID, costGoods.goodsType)
    ---@type goods
    local goods = {
        goodsType = costGoods.goodsType,
        goodsID = costGoods.goodsID,
        goodsNum = costItem.count,
    }
    return goods
end

---@return BingoTaskData[]
function BingoActivityData:GetBingoTaskList()
    ---@type BingoTaskData[]
    local taskList = {}
    if self.taskGroupId == 0 then
        return taskList
    end
    
    local dayTaskList = TaskControl.GetEventRaidTaskData(self.taskGroupId)

    for _, dayTask in pairs(dayTaskList) do
        ---@type BingoTaskData
        local task = {
            taskId = dayTask.id,
            content = dayTask.txt,
            rewards = clone(dayTask.reward),
        }

        local progress, maxProgress = TaskControl.GetTaskProgress(dayTask)
        task.progress = progress
        task.maxProgress = maxProgress

        if dayTask.isComplete == 1 then
            task.state = 2
        elseif dayTask.isReceive == 1 then
            task.state = 1
        else
            task.state = 0
        end
        
        table.insert(taskList, task)
    end

    -- 排序
    ---@param t BingoTaskData
    local GetPriority = function(t)
        if t.state == 2 then
            return 5
        elseif t.state == 1 then
            return 10
        end
        return 0
    end

    ---@param a BingoTaskData
    ---@param b BingoTaskData
    table.sort(taskList, function(a, b)
        local pa = GetPriority(a)
        local pb = GetPriority(b)
        if pa == pb then
            return a.taskId < b.taskId
        else
            return pa > pb
        end
    end)

    return taskList
end

--- 是否还有未翻开的格子
---@param stage int? @ 空则检查所有阶段
---@return boolean
function BingoActivityData:HaveCoveredCell(stage)
    --- 确定阶段范围
    local currentStage = self:GetCurrentStage()
    local bs = currentStage
    local es = self.maxStage
    if stage then
        bs = stage
        es = stage
    end

    local cellCount = self.xLen * self.yLen

    for i = bs, es do
        --- 未解锁阶段，必然有未翻开
        if i > currentStage then
            return true
        end
        
        local stgData = self:_GetStageData(i)
        if stgData then
            if stgData.flippedCount < cellCount then
                return true
            end
        else
            --- 不存在阶段数据，则认为未翻开
            return true
        end
    end
    
    return false
end

--- 确定道具是否足够翻开
---@param stage int? @ 空则检查所有阶段
---@return boolean
function BingoActivityData:HaveFlippableCell(stage)
    --- 未解锁的阶段，都不可翻开
    local currentStage = self:GetCurrentStage()
    if stage and stage > currentStage then
        return false
    end
    
    --- 确定阶段范围
    local bs = 1
    local es = currentStage
    if stage then
        bs = stage
        es = stage
    end

    local cellCount = self.xLen * self.yLen
    
    for i = bs, es do
        local stgData = self:_GetStageData(i)
        local bHaveCover = false
        
        if stgData then
            if stgData.flippedCount < cellCount then
                bHaveCover = true
            end
        else
            -- 阶段数据不存在，则认为均未翻开
            bHaveCover = true
        end

        if bHaveCover then
            --- 检查道具是否充足
            local costGoods = stgData.costGoods
            local costItem = ItemControl.GetItemByIdAndType(costGoods.goodsID, costGoods.goodsType)
            if costGoods.goodsNum <= costItem.count then
                return true
            end
        end
    end
    
    return false
end

---@param stage int
---@param x int
---@param y int
---@return BingoCellData @ 非源数据
function BingoActivityData:GetCellData(stage, x, y)
    -- 不关注有无阶段数据，没有就返回空
    local stgData = self:_GetStageData(stage, true)
    if not stgData then
        return self.BuildEmptyCellData()
    end
    
    local cellData = _StageData_Get(stgData, x, y)
    if not cellData then
        return self.BuildEmptyCellData()
    end
    
    return clone(cellData)
end


function BingoActivityData.BuildEmptyCellData()
    ---@type BingoCellData
    local data = {
        bFlipped = false,
    }
    return data
end


---@protected
function BingoActivityData:_InitStages()
    local maxStage = 1
    
    for _, config in pairs(BingopoolLocalData.tab) do
        if CheckNumber(config[2]) == self.activityId then
            local stage = CheckNumber(config[3])
            maxStage = math.max(maxStage, stage)

            local stgData = self._stages[stage]
            if stgData then
                Global.LogError(string.format("Bingo活动(%s)阶段%s配置(%s)重复", self.activityId, stage, config[1]))
            end
            stgData = _StageData_Build(config)
            self._stages[stage] = stgData
        end
    end
    
    self.maxStage = maxStage
end

---@protected
function BingoActivityData:_InitTask()
    local dayTaskGroupId = 0
    
    for _, config in pairs(BingoeventLocalData.tab) do
        if CheckNumber(config[2]) == self.activityId then
            dayTaskGroupId = CheckNumber(config[4])
            break
        end
    end

    -- 同时起到检查配置存在的要求
    if dayTaskGroupId == 0 then
        Global.LogError(string.format("Bingo活动(%s)配置不存在", self.activityId))
    end
    
    self.taskGroupId = dayTaskGroupId
end

--- 获取阶段数据，通常无阶段数据是不正常的
---@protected
---@param stage int
---@param bNoLog boolean @ 不输出日志
---@return BingoStageData @ 源数据
function BingoActivityData:_GetStageData(stage, bNoLog)
    local data = self._stages[stage]

    if stage > self.maxStage then
        Global.LogError(string.format("尝试获取超过最大阶段(%s)的阶段(%s)数据", self.maxStage, stage))
        return data
    end

    if not bNoLog and not data then
        Global.LogError(string.format("Bingo活动(%s)阶段%s数据不存在", self.activityId, stage))
    end

    return data
end

---@protected
function BingoActivityData:_CalcCurrentStage()
    local currentStage = 1
    
    for i = 1, self.maxStage - 1 do
        local stgData = self._stages[i]
        if not stgData then
            Global.LogError(string.format("Bingo活动(%s)阶段%s数据不存在", self.activityId, i))
            break
        end

        if stgData.flippedCount >= self._upgradeNum then
            currentStage = i + 1
        end
    end

    self._currentStage = currentStage
end

return BingoActivityData
